### ISSUE TITLE
현석님 듀풀이 이해가 안가요....ㅠㅜ

### ISSUE THREAD

**Issue by jungjuyoung** [typescript-study/play-ground#1]
https://github.com/typescript-study/play-ground/blob/4a1de23c467753e3a665c649115fef1bb59f045c/src/01-10-basic-types/basicTypes.ts#L21

**Comment by pocojang** [comment]
튜플은 번역 문서보시면 아시겠지만
배열 요소 모두 통일된 타입이 아닐때 적용하는 거에요!!
하나하나 요소에 각각 타입을 적용하는거죠
