### ISSUE TITLE
약타입보다는 강타입(===) 비교 권장

### ISSUE THREAD

**Issue by pocojang** [typescript-study/play-ground#10]
https://github.com/typescript-study/play-ground/blob/f74c10b521391aec5bc2d28b2f80ec08e048bed4/src/01-10-basic-types/basicTypes.ts#L16

강타입 비교를 권장하구요
더 나아가서 truthy, falsy를 활용해보시는 걸 추천해요!

**Comment by pocojang** [comment]
그리고... 모든 문제 타입스크립트로 전환해주세요!!

**Comment by zadragon** [comment]
코드리뷰 감사합니다 
다시 제출했습니다~
