### ISSUE TITLE
적폐 any를 대체합시다!! any is not TS

### ISSUE THREAD

**Issue by pocojang** [typescript-study/play-ground#7]
https://github.com/typescript-study/play-ground/blob/3fd14b3f76bc612982065490c8df11247c0b50bd/src/01-10-basic-types/basicTypes.ts#L17

**Comment by ysm-dev** [comment]
https://github.com/typescript-study/play-ground/blob/cf3c6fec1e760ba322122bcd84cf3186cdaf2d74/src/01-10-basic-types/basicTypes.ts#L17
수정했습니다 !
