### ISSUE TITLE
trim 사용에 대해서

### ISSUE THREAD

**Issue by pocojang** [typescript-study/play-ground#9]
https://github.com/typescript-study/play-ground/blob/c071b035aa8da72bbe28ba17a5bd9975428b832a/src/01-10-basic-types/basicTypes.ts#L36

이미 반복문을 통해서 입력값에 대한 trim 체크 없이 배열요소들을 한줄의 문자열로 만들었는데
뒤늦게 trim으로 체크하는 것이 의미가 있을까 싶어요!!

**Comment by ghost** [comment]
피드백 감사합니다.

내용 설명 드리자면
배열을 map으로 돌리다 보니 마지막에 빈칸이 들어가서 trim 처리를 했었어요
그러니까 
('string boolean number') <= 이렇게 되어야 하는데
('string boolean number ') <= 이렇게 되는 바람에 trim 처리를 했거든요
현석님 작업하신대로 join으로 처리하는게 더 깔끔할 듯 합니다!

**Comment by pocojang** [comment]
아 그러네요 저는 일일이 체크하는 걸 한번에 한다는 의도로 하신줄 알았습니다!!
